name: Main Build
on:
  push:
    branches:
      - main
      - release/**
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write

concurrency:
  group: terraform

jobs:
  plan:
    uses: curioswitch/cdktf-actions/.github/workflows/main.yaml@2838afabaf55ce4155ce1934d06db14a340a3b99
    with:
      gcp_project_id: tasuke-dev
      gcp_project_number: 720364425367
