name: Main Build
on:
  push:
    branches:
      - main
      - release/**
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write

concurrency:
  group: terraform

jobs:
  plan:
    uses: curioswitch/cdktf-actions/.github/workflows/main.yaml@995e680e4e43e78e0e3e0cd9f9925728564829a6
    with:
      gcp_project_id: tasuke-dev
      gcp_project_number: 720364425367
