name: PR Build
on:
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write

concurrency:
  group: terraform

jobs:
  plan:
    if: github.event.pull_request.head.repo.fork != true
    uses: curioswitch/cdktf-actions/.github/workflows/pr.yaml@83ee91d15e11f470d9a690ee1d2966481caf47ca
    with:
      gcp_project_id: tasuke-dev
      gcp_project_number: 720364425367
