name: PR Build
on:
  pull_request:
    paths-ignore:
      - stacks/sysadmin/**
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write

concurrency:
  group: tf

jobs:
  plan:
    if: github.event.pull_request.head.repo.fork != true
    uses: curioswitch/cdktf-actions/.github/workflows/pr.yaml@ed358eb998e1bc3a1b3e7d7b8057eaa3b2513370
    with:
      gcp_project_id: tasuke-dev
      gcp_project_number: 720364425367
