name: Terraform Plan
on:
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write

concurrency:
  group: terraform

jobs:
  plan:
    if: github.event.pull_request.head.repo.fork != true
    uses: curioswitch/cdktf-actions/pr.yaml@7b95271d159274da2fa945d063ac7a0d32c4fb1d
    with:
      gcp_project_id: tasuke-dev
      workload_identity_provider: projects/720364425367/locations/global/workloadIdentityPools/github/providers/curioswitch
