name: PR Build
on:
  pull_request:
    paths-ignore:
      - stacks/sysadmin/**
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write

concurrency:
  group: tf

jobs:
  plan:
    if: github.event.pull_request.head.repo.fork != true
    uses: curioswitch/cdktf-actions/.github/workflows/pr.yaml@a34a5c1eb67d85c179f2afa009d66ed59f4f18b5
    with:
      gcp_project_id: tasuke-dev
      gcp_project_number: 720364425367
