name: PR Build
on:
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write

concurrency:
  group: terraform

jobs:
  plan:
    if: github.event.pull_request.head.repo.fork != true
    uses: curioswitch/cdktf-actions/.github/workflows/pr.yaml@0d870d9904d292f41c1edde0c7aa080cce00a384
    with:
      gcp_project_id: tasuke-dev
      workload_identity_provider: projects/720364425367/locations/global/workloadIdentityPools/github/providers/curioswitch
