name: PR Build
on:
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write

concurrency:
  group: terraform

jobs:
  plan:
    if: github.event.pull_request.head.repo.fork != true
    uses: curioswitch/cdktf-actions/.github/workflows/pr.yaml@995e680e4e43e78e0e3e0cd9f9925728564829a6
    with:
      gcp_project_id: tasuke-dev
      gcp_project_number: 720364425367
